Repository Orange-OpenSource/ouds-flutter, pull requests merged in 2025-09, with the labels that each got.

#345 feat: update to macos-15 in workflow
  .github/workflows/build.yml
Labels: 🛠️ technical

#340 bug: wrong title for suggestion chip screen (#331)(#212)(#51)
  app/CHANGELOG.md
  app/lib/ui/components/chip/chip_suggestion_demo_screen.dart
  ouds_core/CHANGELOG.md
  ouds_core/lib/components/chip/ouds_suggestion_chip.dart
Labels: 🐞 bug, 📱 demo app, 🧰 library

#372 fix : move dartdoc to dev_dependencies in core (#350)
  ouds_core/CHANGELOG.md
  ouds_core/pubspec.yaml
Labels: 📖 documentation, dependencies, dart
