Repository Orange-OpenSource/ouds-flutter, pull requests merged in 2025-06, with the labels that each got.

#202 194-update-translation-files-to-be-consistent-between-all-mobile-platforms
  app/CHANGELOG.md
  app/lib/l10n/gen/ouds_flutter_app_localizations.dart
  app/lib/l10n/gen/ouds_flutter_app_localizations_ar.dart
  app/lib/l10n/gen/ouds_flutter_app_localizations_en.dart
  app/lib/l10n/ouds_flutter_ar.arb
  app/lib/l10n/ouds_flutter_en.arb
  app/lib/ui/components/button/button_demo_screen.dart
  app/lib/ui/components/components.dart
  app/lib/ui/components/radio_button/radio_button_item_demo_screen.dart
  app/lib/ui/theme/theme_selector.dart
Labels: 📱 demo app, :star: v1.0

#201 133-docs-enrich-components-documentation
  app/CHANGELOG.md
  ouds_core/README.md
  ouds_core/dartdoc_options.yaml
  ouds_core/lib/components/button/ouds_button.dart
  ouds_core/lib/components/checkbox/ouds_checkbox.dart
  ouds_core/lib/components/checkbox/ouds_checkbox_item.dart
  ouds_core/lib/components/divider/ouds_divider.dart
  ouds_core/lib/components/ouds_colored_box.dart
  ouds_core/lib/components/radio_button/ouds_radio_button.dart
  ouds_core/lib/components/radio_button/ouds_radio_button_item.dart
  ouds_core/pubspec.yaml
  ouds_theme_contract/lib/ouds_theme.dart
Labels: 📖 documentation, 🧰 library, :star: v1.0

#230 220 bug delayed pressed state on long texts
  app/CHANGELOG.md
  ouds_core/CHANGELOG.md
  ouds_core/lib/components/button/internal/button_background_modifier.dart
  ouds_core/lib/components/button/internal/button_foreground_modifier.dart
  ouds_core/lib/components/button/internal/button_style_modifier.dart
  ouds_core/lib/components/button/ouds_button.dart
  ouds_core/lib/components/checkbox/ouds_checkbox.dart
  ouds_core/lib/components/control/ouds_control_item.dart
  ouds_core/lib/components/radio_button/ouds_radio_button.dart
Labels: 🐞 bug
